# Generated by Django 4.0.1 on 2022-01-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useravatar',
            options={'verbose_name': 'Аватары', 'verbose_name_plural': 'Аватары'},
        ),
    ]
